### ISSUE TITLE
Bug: Learning_trade.ipynb Please Help

### ISSUE THREAD

**Issue by rsadr** [ucaiado/QLearning_Trading#1]
I have not changed any of the files and Running the example fails for me when I run:

import qtrader.eda as eda; reload(eda);
df_last_pnl = eda.plot_cents_changed(archive, archive2)

program crashes in plot_cents_changed(archive, archive2) with error message:

    424     # filer data
--> 425     na_hour = np.array([x.hour*60 + x.minute for x in quotes.index])
    426     quotes = quotes[(na_hour >= (10 * 60 + 30)) & (na_hour <= (16 * 60 + 30))]
    427     na_days = np.array([x.day for x in quotes.index])

AttributeError: 'tuple' object has no attribute 'hour'

**Comment by ucaiado** [comment]
@rsadr, the codes in the notebook are not in the same version of the project. Please follow the instructions in the README to use the agent.

**Comment by rsadr** [comment]
I already followed your READ.md

python agent.py test_random
Traceback (most recent call last):
  File "agent.py", line 35, in <module>
    logging.basicConfig(filename=s_file, format=s_format)
  File "/usr/lib/python2.7/logging/__init__.py", line 1554, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)

**Comment by ucaiado** [comment]
I believe that it was an IO error, right? Try to run in the top-level project directory (in the folder above qtrader/) this command:
`python -m qtrader.agent test_random`

**Comment by rsadr** [comment]
Same problem

python -m qtrader.agent test_random
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rs/Downloads/Pandas-Cookbook-master/QLearning_Trading-master/qtrader/agent.py", line 35, in <module>
    logging.basicConfig(filename=s_file, format=s_format)
  File "/usr/lib/python2.7/logging/__init__.py", line 1554, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)

**Comment by ucaiado** [comment]
what is the last line of this error message? Maybe you have to create the path to the log file.

**Comment by rsadr** [comment]
I tried again with setting path for log with no success. Same error with last line
IOError: [Errno 2] No such file or directory: ..//QLearning_Trading-master/log/train_test/sim_Wed_Sep_18_185221_2019.log'

I cannot make a dummy file as I do not know what this file format looks like

**Comment by ucaiado** [comment]
Have you already created this folder `../QLearning_Trading-master/log/train_test/`?

**Comment by rsadr** [comment]
OK I got it going by exporting the path for the executable and explicitly mkdir for train_test

Thanks for your help
